quarkus.http.port=8080
quarkus.package.jar.type=uber-jar

firebase.project-id=gestionproyectosuniversitarios
quarkus.oidc.enabled=true
quarkus.oidc.auth-server-url=https://securetoken.google.com/${firebase.project-id}
quarkus.oidc.client-id=${firebase.project-id}
quarkus.oidc.application-type=service
quarkus.oidc.token.issuer=https://securetoken.google.com/${firebase.project-id}
quarkus.oidc.token.audience=${firebase.project-id}
quarkus.oidc.authentication.user-info-required=false
quarkus.http.auth.permission.health.paths=/api/health,/q/health
quarkus.http.auth.permission.health.policy=permit
quarkus.http.auth.permission.preflight.paths=/*
quarkus.http.auth.permission.preflight.methods=OPTIONS
quarkus.http.auth.permission.preflight.policy=permit
quarkus.http.auth.permission.api.paths=/api/*
quarkus.http.auth.permission.api.policy=authenticated

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:5173,http://127.0.0.1:5173
quarkus.http.cors.methods=GET,POST,PUT,PATCH,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,x-requested-with
quarkus.http.cors.access-control-allow-credentials=true

health.rest.uri=http://localhost:8081
proyectos.rest.uri=http://localhost:8082
tareas.rest.uri=http://localhost:8083
usuarios.rest.uri=http://localhost:8084
informes.rest.uri=http://localhost:8085

quarkus.rest-client.health-api.url=${health.rest.uri}
quarkus.rest-client.proyectos-api.url=${proyectos.rest.uri}
quarkus.rest-client.tareas-api.url=${tareas.rest.uri}
quarkus.rest-client.usuarios-api.url=${usuarios.rest.uri}
quarkus.rest-client.informes-api.url=${informes.rest.uri}
