quarkus.http.port=8084
quarkus.package.jar.type=uber-jar

firebase.project-id=gestionproyectosuniversitarios
quarkus.oidc.enabled=true
quarkus.oidc.auth-server-url=https://securetoken.google.com/${firebase.project-id}
quarkus.oidc.client-id=${firebase.project-id}
quarkus.oidc.application-type=service
quarkus.oidc.token.issuer=https://securetoken.google.com/${firebase.project-id}
quarkus.oidc.token.audience=${firebase.project-id}
quarkus.oidc.authentication.user-info-required=false
quarkus.http.auth.permission.public.paths=/api/universidades
quarkus.http.auth.permission.public.policy=permit
quarkus.http.auth.permission.api.paths=/api/*
quarkus.http.auth.permission.api.policy=authenticated

database.host=localhost
database.port=5433
database.name=tfg_proyectos
database.username=tfg
database.password=tfg_secret

quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql://${database.host}:${database.port}/${database.name}
quarkus.datasource.username=${database.username}
quarkus.datasource.password=${database.password}

# OpenAPI / Swagger UI
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui
quarkus.smallrye-openapi.path=/q/openapi
quarkus.http.auth.permission.openapi.paths=/q/openapi,/q/swagger-ui,/q/swagger-ui/*
quarkus.http.auth.permission.openapi.policy=permit
